apiVersion: v1
kind: Namespace
metadata:
  name: below-system
  labels:
    name: below-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: below-config
  namespace: below-system
data:
  below.conf: |
    log_dir = "/var/log/below"
    store_dir = "/var/log/below/store"
    enable_btrfs_stats = false
    enable_gpu_stats = false
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: below
  namespace: below-system
  labels:
    k8s-app: below
spec:
  selector:
    matchLabels:
      app: below
  template:
    metadata:
      labels:
        app: below
    spec:   
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                k8s-app: below
            topologyKey: kubernetes.io/hostname
      tolerations:
      - operator: Exists
      containers:
      - name: below
        image: dinoallo/below:v0.9.0
        env:
        - name: RUST_LIB_BACKTRACE
          value: "1"
        command: ["/usr/local/bin/below"]
        args:
        - --config=/etc/below/below.conf
        - record
        - --compress
        - --collect-io-stat
        - --dict-compress-chunk-size=16
        - --store-size-limit=524288000
        - --retain-for-s=604800
        volumeMounts:
        - name: below-log
          mountPath: /var/log/below
        - name: below-store
          mountPath: /var/log/below/store
        - name: below-config
          mountPath: /etc/below/below.conf
          subPath: below.conf
        securityContext:
          # capabilities:
          #   add:
          #   - NET_ADMIN
          #   - SYS_MODULE
          #   - SYS_ADMIN
          #   - SYS_RESOURCE
          #   drop:
          #   - ALL
          privileged: true
      volumes:
      - name: below-log
        hostPath:
          path: /var/log/below
          type: DirectoryOrCreate
      - name: below-store
        hostPath:
          path: /var/log/below/store
          type: DirectoryOrCreate
      - name: below-config
        configMap:
          name: below-config
          items:
          - key: below.conf
            path: below.conf
